### ISSUE TITLE
Past Classes Bug

### ISSUE THREAD

**Issue by ArmaanS211** [SumitNalavade/FriscoISDHACAPI#5]
Hey, I was testing out this API, I tried out the past classes but it only shows the most current quarter grades(4th quarter) no matter the quarter

**Comment by SumitNalavade** [comment]
Investigating this now. Will notify you when issue is resolved

**Comment by SumitNalavade** [comment]
@ArmaanS211 Should be fixed now. Please let me know if there are any more issues that come up. Thanks!
