### ISSUE TITLE
Past Classes returning current quater

### ISSUE THREAD

**Issue by Someone-Alive** [SumitNalavade/FriscoISDHACAPI#6]
Hi, whenever I try to request for a different quarter, it only returns the current quarter (2nd) classes and assignments instead of the requested quarter

**Comment by SumitNalavade** [comment]
Thank you for letting me know, working on a fix now!

**Comment by SumitNalavade** [comment]
@Someone-Alive Issue should be resolved now, passing in the quarter returns all of the classes and assignments for that quarter. Please let me know if you experience any further issues!
